import { typography, layout } from './typography.js';
import chalk from 'chalk';
import inquirer from 'inquirer';

/**
 * MCP Tools available in VulnZap
 */
const MCP_TOOLS = [
    {
        name: 'auto-vulnerability-scan',
        title: 'Auto Vulnerability Scan',
        icon: '🛡️',
        description: 'Automatically scans code generated by your AI assistant for security vulnerabilities in real-time',
        benefit: 'Catches security issues before they reach your codebase',
        demo: 'When your AI suggests code, VulnZap instantly analyzes it for common vulnerabilities like SQL injection, XSS, and insecure dependencies.'
    },
    {
        name: 'scan_repo',
        title: 'Repository Scanner',
        icon: '📂',
        description: 'Performs comprehensive security audits of your entire repository',
        benefit: 'Identifies vulnerabilities across your entire codebase',
        demo: 'Scans all files in your project, including dependencies, to create a complete security report with actionable fixes.'
    },
    {
        name: 'check_package',
        title: 'Package Security Checker',
        icon: '📦',
        description: 'Validates the security of npm packages, pip modules, and other dependencies',
        benefit: 'Prevents vulnerable dependencies from entering your project',
        demo: 'Before installing a package, VulnZap checks it against known vulnerability databases and provides safe alternatives.'
    },
    {
        name: 'get_fix_suggestion',
        title: 'AI Fix Suggestions',
        icon: '🔧',
        description: 'Generates AI-powered code fixes for detected vulnerabilities',
        benefit: 'Automatically resolves security issues with context-aware fixes',
        demo: 'When a vulnerability is found, VulnZap provides a ready-to-apply patch with explanations of what changed and why.'
    },
    {
        name: 'security_context',
        title: 'Security Context',
        icon: '🧠',
        description: 'Provides your AI assistant with security best practices and guidelines',
        benefit: 'Helps your AI write more secure code from the start',
        demo: 'Your AI assistant gains knowledge of security patterns, making it suggest safer implementations automatically.'
    }
];

/**
 * Display the Tool Spotlight - Interactive tour of MCP tools
 */
export async function displayToolSpotlight() {
    layout.clear();
    layout.section();

    // Welcome
    console.log(typography.header('  Tool Spotlight'));
    console.log(typography.subheader('  Discover the 5 powerful security tools now available to your AI'));
    layout.section();

    // Overview
    console.log(typography.body('  VulnZap adds security superpowers to your AI assistant through'));
    console.log(typography.body('  the Model Context Protocol (MCP).'));
    layout.spacer();
    console.log(typography.dim('  Here\'s what\'s now available:'));
    layout.section();

    // Interactive tour
    for (let i = 0; i < MCP_TOOLS.length; i++) {
        const tool = MCP_TOOLS[i];
        await displayTool(tool, i + 1, MCP_TOOLS.length);

        // Ask if they want to continue (except for the last tool)
        if (i < MCP_TOOLS.length - 1) {
            const { continue: shouldContinue } = await inquirer.prompt([
                {
                    type: 'confirm',
                    name: 'continue',
                    message: 'Continue to next tool?',
                    default: true
                }
            ]);

            if (!shouldContinue) {
                break;
            }

            layout.clear();
            layout.section();
        }
    }

    // Completion
    layout.section();
    console.log(typography.success('  ✓ Tool Spotlight Complete'));
    layout.spacer();
    console.log(typography.body('  These tools are now active in your IDE.'));
    console.log(typography.dim('  Your AI assistant can use them automatically.'));
    layout.section();
}

/**
 * Display a single tool in the spotlight
 */
async function displayTool(tool: typeof MCP_TOOLS[0], index: number, total: number) {
    // Tool header
    console.log(typography.dim(`  ─── Tool ${index} of ${total} ───`));
    layout.spacer();

    console.log(typography.header(`  ${tool.icon}  ${tool.title}`));
    console.log(typography.dim(`  (${tool.name})`));
    layout.spacer();

    // Description
    console.log(typography.body(`  ${tool.description}`));
    layout.spacer();

    // Benefit
    console.log(typography.accent('  Why it matters:'));
    console.log(typography.dim(`  ${tool.benefit}`));
    layout.spacer();

    // Demo example
    console.log(typography.accent('  How it works:'));
    console.log(typography.dim(`  ${tool.demo}`));
    layout.spacer();
}

/**
 * Quick summary of all tools (non-interactive)
 */
export function displayToolSummary() {
    layout.section();
    console.log(typography.header('  MCP Tools Enabled'));
    layout.spacer();

    MCP_TOOLS.forEach((tool, index) => {
        console.log(typography.dim(`  ${tool.icon} ${tool.title}`));
    });

    layout.spacer();
    console.log(typography.dim('  Run "vulnzap tools" to learn more about each tool.'));
    layout.section();
}
